<a href="https://colab.research.google.com/github/zeroing2/Colab/blob/master/%EC%97%AC%EB%9F%AC%EA%B0%9C%EC%9D%98_%EC%9E%85%EB%A0%A5%EC%97%90_%EB%8C%80%ED%95%9C_Linear_Regression1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [62]:
import sys
import tensorflow as tf

print("python version: ", sys.version)
print("tensorflow version: ", tf.__version__)

python version:  3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0]
tensorflow version:  1.15.0


In [63]:
x_data = [[73., 80., 75.], [93., 88., 93.], [89, 91, 90], [96, 98, 100], [73, 66, 70]]
y_data = [[152.], [185.], [180.], [196.], [142.]]

print("x_data: ", x_data)
print("y_data: ", y_data)

x_data:  [[73.0, 80.0, 75.0], [93.0, 88.0, 93.0], [89, 91, 90], [96, 98, 100], [73, 66, 70]]
y_data:  [[152.0], [185.0], [180.0], [196.0], [142.0]]


In [64]:
# placefholders for a tensor that will be always fed
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

print("X: ", X)
print("Y: ", Y)
print("W: ", W)
print("b: ", b)

X:  Tensor("Placeholder_27:0", shape=(?, 3), dtype=float32)
Y:  Tensor("Placeholder_28:0", shape=(?, 1), dtype=float32)
W:  <tf.Variable 'weight_8:0' shape=(3, 1) dtype=float32_ref>
b:  <tf.Variable 'bias_4:0' shape=(1,) dtype=float32_ref>


In [65]:
# Our hypothesis
hypothesis = tf.matmul(X, W) + b
# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize: Gradient Descent Magic
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session
sess = tf.Session()
# Initialize global variables in the graph
sess.run(tf.global_variables_initializer())

for step in range(500001):
  cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
  if step % 50000 == 0:
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  3795.8562 
Prediction:
 [[102.467186]
 [115.42314 ]
 [117.944374]
 [125.24981 ]
 [ 88.81774 ]]
50000 Cost:  0.23639071 
Prediction:
 [[151.79253]
 [184.50327]
 [180.80804]
 [195.64366]
 [142.33504]]
100000 Cost:  0.1661655 
Prediction:
 [[151.61797]
 [184.58429]
 [180.70381]
 [195.95203]
 [142.12004]]
150000 Cost:  0.15963422 
Prediction:
 [[151.56665]
 [184.608  ]
 [180.672  ]
 [196.04413]
 [142.05647]]
200000 Cost:  0.1587383 
Prediction:
 [[151.55171]
 [184.61487]
 [180.66167]
 [196.07158]
 [142.03842]]
250000 Cost:  0.15833981 
Prediction:
 [[151.54765]
 [184.61667]
 [180.6577 ]
 [196.08034]
 [142.0334 ]]
300000 Cost:  0.15797858 
Prediction:
 [[151.5473 ]
 [184.61674]
 [180.65588]
 [196.08243]
 [142.0331 ]]
350000 Cost:  0.1576273 
Prediction:
 [[151.54778]
 [184.61642]
 [180.65456]
 [196.0832 ]
 [142.03365]]
400000 Cost:  0.15727776 
Prediction:
 [[151.54843]
 [184.616  ]
 [180.65332]
 [196.08371]
 [142.03438]]
450000 Cost:  0.15692379 
Prediction:
 [[151.54904]
 [184.61